version: '2'

services:


    omscore-nginx:
        image: aegee/omscore-nginx:dev
        volumes_from:
            - omscore-data
        links:
            - php-fpm
        expose:
            - "80"
        labels:
            - "traefik.backend=omscore"
            - "traefik.port=80"
            - "traefik.frontend.rule=HostRegexp:{domain:[a-z0-9.]+}"
            - "traefik.frontend.priority=10"
            - "traefik.enable=true"
            - "registry.categories=(users, 10);(antennae, 10);(notifications, 0)"
            - "registry.backend=/api"
            - "registry.description=The core module with both backend and frontend"


    omsevents:
        image: aegee/omsevents:dev
        volumes:
            - omsevents_media:/usr/app/media
            - "../oms-events:/usr/app/oms-events"
            - shared:/usr/shared:ro
        links:
            - mongodb
        expose:
            - "8082"
        labels:
            - "traefik.backend=omsevents"
            - "traefik.port=8082"
            - "traefik.frontend.rule=HostRegexp:{domain:[a-z]+};PathPrefix:/services/omsevents/api;PathPrefixStrip:/services/omsevents/api"
            - "traefik.frontend.priority=110"
            - "traefik.enable=true"
            - "registry.categories=(events, 10);(notifications, 10)"
            - "registry.servicename=omsevents"



    omsevents-frontend:
        image: aegee/omsevents-frontend:dev
        volumes:
            - "../oms-events-frontend:/usr/app/frontend:ro"
            - omsevents_media:/usr/app/media
        expose:
            - "8083"
        labels:
            - "traefik.frontend.rule=HostRegexp:{domain:[a-z]+};PathPrefix:/services/omsevents;PathPrefixStrip:/services/omsevents"
            - "traefik.frontend.priority=100"
            - "traefik.port=8083"
            - "traefik.backend=omsevents-frontend"
            - "traefik.enable=true"
            - "registry.modules=/frontend/getModules.json"


#    omsapplications:
#        image: aegee/omsapplications:dev
#        volumes:
#            - "../oms-applications:/usr/app"
#            - shared:/usr/shared:ro
#        links:
#            - mongodb
#        expose:
#            - "8085"
#        labels:
#            - "traefik.backend=omsapplications"
#            - "traefik.port=8085"
#            - "traefik.frontend.rule=HostRegexp:{domain:[a-z]+};PathPrefix:/services/omsapplications/api;PathPrefixStrip:/services/omsapplications/api"
#            - "traefik.frontend.priority=110"
#            - "traefik.enable=true"
#            - "registry.categories=(applications, 10);(events_frontend, 10)"
#            - "registry.servicename=omsapplications"
#
#
#    omsapplications-frontend:
#        image: aegee/omsapplications-frontend:dev
#        volumes:
#            - "../oms-applications-frontend:/usr/app:ro"
#        expose:
#            - "8086"
#        labels:
#            - "traefik.frontend.rule=HostRegexp:{domain:[a-z]+};PathPrefix:/services/omsapplications;PathPrefixStrip:/services/omsapplications"
#            - "traefik.frontend.priority=100"
#            - "traefik.port=8086"
#            - "traefik.backend=omsapplications-frontend"
#            - "traefik.enable=true"
#            - "registry.modules=/getModules.json"


### Volumes Setup ###########################################

volumes:
    postgres:
        driver: "local"
    mongodb:
        driver: "local"
    omsevents_media:
        driver: "local"
    shared:
        driver: "local"
