version: '3.2'

services:
    omsserviceregistry:
        image: aegee/omsserviceregistry:dev
        ports:
            - "7000:7000"
        volumes:
            - ./oms-serviceregistry:/usr/src/app
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - shared:/usr/src/shared
        links:
            - mongodb

    mongodb:
        image: mongo:latest
        expose:
            - "27017"
        volumes:
            - mongodb:/data/db

volumes:
    mongodb:
        driver: "local"
    shared:
        driver: "local"
