version: '3.2'

services:

### OMS SERVICE REGISTRY        #######################################
    omsserviceregistry:
        build:
            context: ./$PATH_OMS_REGISTRY/omsserviceregistry/
            dockerfile: ./Dockerfile.dev
        image: aegee/omsserviceregistry:dev
        ports:
            - "7000:7000"
        volumes:
            - type: bind
              source: ./$PATH_OMS_REGISTRY/../
              target: /usr/src/app
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
              read_only: true
            - type: volume
              source: shared
              target: /usr/src/shared
        links:
            - mongodb
        labels:
            - "registry.port=7000"

    mongodb:
        image: mongo:latest
        expose:
            - "27017"
        volumes:
            - type: volume
              source: mongodb
              target: /data/db


volumes:
    mongodb:
        driver: "local"
    shared:
        driver: "local"

networks:
  default:
    external:
      name: OMS
