FROM node:8

RUN mkdir -p /usr/app/shared && mkdir -p /usr/app/src && mkdir -p /usr/app/scripts

ADD ./bootstrap.sh /usr/app/scripts/bootstrap.sh

WORKDIR /usr/app/src

CMD sh /usr/app/scripts/bootstrap.sh && node /usr/app/src/index.js
